### ISSUE TITLE
car and bike Single page, order tracking detail page - Shrey Jajal

### ISSUE THREAD

**Issue by shikhu51197** [shikhu51197/sigmapractice#9]
1. [x] single page 

- [x] multiple image of product  and detail of that product
- [x]  show 3 similar products 

2. [x] order tracking detail page 

- [x] order details img , price , location , quantity , ship deliver expected delivery
